apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  template:

    metadata:
      name: web
      labels:
        app: web
    spec:
      hostNetwork: true
      containers:
        - name: web
          image: subaruqui/poc
          ports:
            - containerPort: 8000
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: web
